//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRABAJADORES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public Nullable<decimal> SueldoBruto { get; set; }
        public string Categoria { get; set; }
    }
}
